--------------------------------------------------------
--  파일이 생성됨 - 금요일-9월-25-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_RESULTNO
--------------------------------------------------------

   CREATE SEQUENCE  "PRIVATE"."SEQ_RESULTNO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USER_NO
--------------------------------------------------------

   CREATE SEQUENCE  "PRIVATE"."SEQ_USER_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table RESULT
--------------------------------------------------------

  CREATE TABLE "PRIVATE"."RESULT" 
   (	"RESULTNO" NUMBER, 
	"USERNO" NUMBER, 
	"MEASUREDATE" DATE, 
	"CATEGORY" VARCHAR2(50 BYTE), 
	"STABLE" NUMBER(3,2), 
	"SPEED20" NUMBER(3,2), 
	"SPEED25" NUMBER(3,2), 
	"SPEED30" NUMBER(3,2), 
	"SPEED35" NUMBER(3,2), 
	"SPEED40" NUMBER(3,2), 
	"SPEED45" NUMBER(3,2), 
	"SPEED50" NUMBER(3,2), 
	"RECOVERY5MIN" NUMBER(3,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "PRIVATE"."USERS" 
   (	"USERNO" NUMBER, 
	"USERID" VARCHAR2(80 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"USERTYPE" VARCHAR2(20 BYTE), 
	"GENDER" VARCHAR2(10 BYTE), 
	"WEIGHT" NUMBER(5,0), 
	"HEIGHT" NUMBER(5,0), 
	"ADMINNO" NUMBER, 
	"FIELD" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PRIVATE.RESULT
SET DEFINE OFF;
REM INSERTING into PRIVATE.USERS
SET DEFINE OFF;
Insert into PRIVATE.USERS (USERNO,USERID,PASSWORD,NAME,USERTYPE,GENDER,WEIGHT,HEIGHT,ADMINNO,FIELD) values (1,'id1','1234','백이름','athlete','female',61,173,6,'a');
Insert into PRIVATE.USERS (USERNO,USERID,PASSWORD,NAME,USERTYPE,GENDER,WEIGHT,HEIGHT,ADMINNO,FIELD) values (2,'id2','1234','권이름','athlete','female',67,177,6,'b');
Insert into PRIVATE.USERS (USERNO,USERID,PASSWORD,NAME,USERTYPE,GENDER,WEIGHT,HEIGHT,ADMINNO,FIELD) values (3,'id3','1234','윤이름','athlete','male',86,178,6,'c');
Insert into PRIVATE.USERS (USERNO,USERID,PASSWORD,NAME,USERTYPE,GENDER,WEIGHT,HEIGHT,ADMINNO,FIELD) values (4,'id4','1234','정이름','athlete','male',73,176,6,'d');
Insert into PRIVATE.USERS (USERNO,USERID,PASSWORD,NAME,USERTYPE,GENDER,WEIGHT,HEIGHT,ADMINNO,FIELD) values (5,'id5','1234','최이름','athlete','male',85,185,6,'e');
Insert into PRIVATE.USERS (USERNO,USERID,PASSWORD,NAME,USERTYPE,GENDER,WEIGHT,HEIGHT,ADMINNO,FIELD) values (6,'admin01','1234','손주연','admin','female',0,0,0,null);
Insert into PRIVATE.USERS (USERNO,USERID,PASSWORD,NAME,USERTYPE,GENDER,WEIGHT,HEIGHT,ADMINNO,FIELD) values (9,'1번','12345','손주연','athlete','female',158,57,6,'마라톤');
Insert into PRIVATE.USERS (USERNO,USERID,PASSWORD,NAME,USERTYPE,GENDER,WEIGHT,HEIGHT,ADMINNO,FIELD) values (7,'admin02','1234','교수1','admin','male',0,0,0,null);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "PRIVATE"."USERS" ADD UNIQUE ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PRIVATE"."USERS" ADD PRIMARY KEY ("USERNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PRIVATE"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table RESULT
--------------------------------------------------------

  ALTER TABLE "PRIVATE"."RESULT" ADD CONSTRAINT "FK_USER_NO" FOREIGN KEY ("USERNO")
	  REFERENCES "PRIVATE"."USERS" ("USERNO") ENABLE;
